spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}/${DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MariaDB103Dialect

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-Key: ${AWS_ACCESS}
      secret-Key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}